# Generated by Django 4.2.7 on 2023-11-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('nom_team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=256)),
                ('est_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.user')),
            ],
            options={
                'unique_together': {('user', 'team')},
            },
        ),
    ]
